server {
    listen 80;

    # 1. Dieu huong cho Frontend (Trang chu)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Dieu huong cho API Backend (Cac yeu cau du doan)
    location /predict {
        proxy_pass http://backend-api:5000/predict;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}